### PR TITLE
Added a default capstyle for boxplot median lines

### PR DESCRIPTION
**Pull request by shaibalmuhtadee**
## PR Summary
Set the default capstyle for boxplot median lines to the 'butt' to prevent overlapping bug

## PR Checklist
- [x] Make sure the code runs
- [x] Make sure it doesn't hinder any other code

**Documentation and Tests**
- [x] Code Review and Tested Prior to Merge
- [x] Well documented code

### CODE REVIEW

**Comment by nafiomiah** [comment]
Looks good to me! I'll add a test for this to verify that it works.

**Comment by nafiomiah** [comment]
@shaibalmuhtadee, hey I added a test, can you verify it? [#f9d442f](https://github.com/FahimRT/group26-oss-matplotlib/pull/2/commits/f9d442f97de6440d2118b2d28a3779ef9c126c28)

**Comment by shaibalmuhtadee** [comment]
> @shaibalmuhtadee, hey I added a test, can you verify it? [#f9d442f](https://github.com/FahimRT/group26-oss-matplotlib/pull/2/commits/f9d442f97de6440d2118b2d28a3779ef9c126c28)

Yeah I can verify the test for you!

**Review by shaibalmuhtadee — COMMENTED** [review]
Looks good to me!

**Comment by nafiomiah** [comment]
@shaibalmuhtadee, thanks for reviewing the test. You can go ahead and merge this pull request.

**Pull request merged**
